on:
  workflow_call:
    inputs:
      rspec_setup_command:
        required: false
        type: string
jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      RACK_ENV: test
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - if: ${{ inputs.rspec_setup_command != '' }}
        run: ${{ inputs.rspec_setup_command }}
      - run: bundle exec rspec
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rubocop
